- .eslintrc.js
- package-lock.json
- package.json
- src/configurations.ts
- src/database/app-sequelize.ts
- src/database/index.ts
- src/database/models/permission.ts
- src/database/models/session.ts
- src/database/models/university.ts
- src/database/models/user.ts
- src/exceptions/already-exists-error.ts
- src/exceptions/no-associated-university-error.ts
- src/features/permissions/roles.ts
- src/features/universities/university-controller.ts
- src/features/users/user-controller.ts
- src/features/users/user-route-validation.ts
- src/features/users/user-route.ts
- src/index.ts
- src/middleware/auth.ts
- src/middleware/joi-validator.ts
- src/routes.ts
- src/server.ts
- src/utilities/email-helper.ts
- src/utilities/encryption-helper.ts
- src/utilities/http-response.ts
- src/utilities/logger.ts
Added nodemon for quicker auto restarts and quicker deployment
Added response formatting to limiter
Added failure case to account verification
Added linter
Fixed all linting issues
Fixed register call to not return sensitive cases
Added awaits for startup to avoid errors
Added permission model
Added permission logic on register
> Project setup

- src/features/users/user-route.ts
This is just a nice personalization touch, and makes sure we are logged in correctly.
> Added the username as part of the fields returned to the frontend.

- src/features/courses/course-controller.ts
- src/features/courses/course-route-validation.ts
- src/features/courses/course-route.ts
> Added route for getting a list of topics

- src/utilities/renderer-helper.ts
> change problem rendering template

- src/features/courses/course-controller.ts
- src/features/courses/course-route.ts
This allows the topic question page to render the appropriate icon (to
match historic responses)
> Frontend Issue #48 Added extra response data to submitting a grade

- src/features/courses/course-controller.ts
The student enrollment was being created at the time of search for
necessary grades to complete
> Issue #41 Fixed timing issue

- src/extensions/index.ts
- src/extensions/sequelize-errors-extension.ts
- src/features/courses/course-controller.ts
- src/features/curriculum/curriculum-controller.ts
There is a follow up PR where more issues were fixed after fixing all strict issues and additional cleanup
> Sequelize error extension

- src/features/courses/course-controller.ts
Added wrapped exception to get clearer stack trace
Stringified the submitted field to handle workbooks
> RED-92 Fixed unicode error

- src/features/courses/course-controller.ts
Fixed issue where syncing grades was not looking for grades that
corresponded with the enrollment
> Fixed syncing grades issue

- package.json
- src/database/migrations/20200925034242-assessments-setup.ts
- src/database/models/course-question-assessment-info.ts
- src/database/models/student-grade-instance.ts
- src/database/models/student-grade.ts
- src/database/models/student-topic-assessment-override.ts
- src/database/models/topic-assessment-info.ts
- src/features/courses/course-controller.ts
- src/features/courses/course-repository.ts
- src/features/courses/course-route.ts
- src/features/courses/course-types.ts
preliminary pull request to compliment branch of the same name on the frontend:
- students will be asked to take a new version if they don't have one open
- students problem states save and can be submitted
- grade results are shown in a modal according to the exam settings
- after an exam is over, problems will be hidden and a new version will need to be started
- backend will not comply when the delay hasn't passed yet, but the front end isn't ready for that
- exceeding the number of allowed graded attempts per version makes the back end err, but the message doesn't make it beyond STDERR
- there are only backend checks against exceeding the allowed number of versions
- an exam version cannot be ended early yet
> RED-144 updates for submit exam + response

- src/features/utility/utility-route-request-types.ts
- src/features/utility/utility-route-validation.ts
- src/features/utility/utility-route.ts
- src/routes.ts
Moved version endpoint to utility function as well
> RED-180 Added route for logging client side errors

- src/features/courses/course-controller.ts
- src/features/users/user-controller.ts
remove reference to stripped rendererResponse data
update studentGrade.numAttempts to reflect number of distinct versions attempted
> update StudentGrade numAttempts for exams

- src/features/courses/course-controller.ts
- src/features/courses/course-route.ts
- src/features/courses/course-types.ts
improved error handling on getting question(s)
> throw errors instead of Boom

- src/database/models/student-grade-instance.ts
- src/features/courses/course-controller.ts
merge this first - student-grade-instance update (included here) was left off of RED-214 PR
> RED-217 update grade instance fields with assessment score

- src/features/courses/course-controller.ts
null.[0].prop is bad ...mmmkay?
> RED-222 fix:

- src/features/courses/course-route.ts
Also fixed mistake in delete message
> RED-125 Added base url to the attachments response

- src/database/models/course.ts
- src/features/courses/course-controller.ts
- src/features/courses/course-route-request-types.ts
- src/features/courses/course-route-validation.ts
- src/features/courses/course-route.ts
- src/features/courses/course-types.ts
- src/utilities/email-helper.ts
Also updated the reply-to header in the mailer so professors can easily reply to the student.
> Added enpoint to allow students to email the professor of a course.

- src/playground/playground-renderer-functions.ts
- src/playground/playground-scheduler-functions.ts
- src/utilities/renderer-helper.ts
Also included playground function I used to test it out
> RED-232 Added read and write renderer calls to renderer helper

- src/cli.ts
- src/global-error-handlers.ts
- src/index.ts
- src/playground/playground.ts
If a promise or an error go unhandled we log the error
> RED-262 add global event listeners for errors

- src/features/courses/course-controller.ts
If you are enrolling in a course that you are already enrolled in the
existing enrollment is returned
> RED-288 Return enrolled course if already enrolled

- src/features/utility/utility-route.ts
Before we were only accepting errors
Now it will try to use the log level provided otherwise default to error
> RED-290 made logging utility respect log level

- src/features/courses/course-controller.ts
for exam submission - grades / grade instances have non-null workbook ids on first submit
> first attempts always set influencing workbook ids

- src/database/migrations/20201118202558-user-uuid.ts
- src/database/models/user.ts
- src/features/courses/course-controller.ts
- src/features/courses/course-route.ts
- src/features/users/user-controller.ts
- src/features/users/user-route.ts
Make sure to review my other pr first otherwise you will be double reviewing changes
> Feature/red 301 user UUID

- src/features/courses/course-controller.ts
- src/utilities/renderer-helper.ts
> block workbook creation on duplicate submission

- src/extensions/rederly-express-request.ts
- src/features/courses/course-route.ts
- src/features/users/user-controller.ts
- src/middleware/auth.ts
- src/server.ts
This branch is based on RED-321, do not review until it has been merged...
> Feature/red 329 restrict unpaid (based on RED-321)

- .github/workflows/build-release.yaml
- .github/workflows/test.yaml
- package.js
all node_modules in parent directories get checked too
so by preserving the node modules I invalidated the test
> Fixed issue where package check didn't check anything

- src/cli.ts
active topics and updates that object's associated error object.
> Added a CLI command that checks all question/assessmentinfo paths in

- src/utilities/file-helper.ts
- src/utilities/webwork-utilities/importer.ts
This is not a bug in our system but us catering to a bug where spaces
get stripped from def files
> RED-368 Work around for def files that strip spaces out

- src/features/courses/course-controller.ts
- src/features/courses/course-route.ts
- src/features/courses/course-types.ts
This includes a link to the problem
And the course and unit this problem belongs to
> RED-454 Added more info to email prof

- src/features/courses/course-route.ts
- src/features/users/user-controller.ts
- src/features/users/user-route.ts
Used email instead of preferred email
Also added a poor man's template to give instructions to the student
> RED-485 Fixed reply to from email students
